# fly.toml app configuration file generated for movies-list-api on 2023-10-15T23:17:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "movies-list-api"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[signal]
  command = "npm start"
  signal = "SIGTERM"